### ISSUE TITLE
Epic: accessibility for the "People Listing"

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#324]
Here's what all needs to be fixed to make the "People Listing" accessible, based on [the WAVE tool report for the faculty page](http://wave.webaim.org/report#/http://isaw.nyu.edu/people/faculty/isaw-faculty):

- [x] headshot images do not have ```alt``` attributes
  - #325 (add empty "alt" attributes to ```span.facultyImage > img``` in "People Listing")
- [x] in each ```<div class="facultyListing">```, there should be only one link to the profile
  - #335 (eliminate redundant links in the people listing)
- [x] there is a weird empty paragraph tag in each facultyListing div
  - #327 (fix bad "People Listing" markup for "position")
- [x] ```<h1>``` and ```<h3>``` are misapplied in the header, disrupting page hierarchy
  - #326 (improve hierarchy and and link structure in header on pages other than home)
- [x] page title/ section title is a mess
   - #333 (Eliminate page-title/section-title markup at end of header)
- [x] search icon and search text have redundant links (site-wide?)
  - #250: Hide advanced search from screen readers
- [x] redundant ```title``` attributes on links in header navigation (site-wide)
   - #331 (eliminate all title attributes on links in header navigation)

**Comment by paregorios** [comment]
this epic is complete
