### ISSUE TITLE
Epic: accessibility for People Profiles

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#330]
We need to make the custom content type we use for the profiles in the ```/people``` section fully accessible.

Here's what all needs to be fixed to make our profiles accessible, based on the WAVE tool reports for multiple pages:

- [x] headshot images do not have ```alt``` attributes
  - #332 (add empty "alt" attributes to "div.profileImage" > img in "Profile" objects)
- [x] ```<h1>``` and ```<h3>``` are misapplied in the header, disrupting page hierarchy
  - #326 (improve hierarchy and and link structure in header on pages other than home)
- [x] "page-title" and "section-title" are confused and incorrectly make use of ```<h2>```
   - #333 (eliminate page-title/section-title markup at end of header)
- [x] search icon and search text have redundant links (site-wide?)
  - #250 (hide advanced search from screen readers)

**Comment by paregorios** [comment]
this epic is complete
