### ISSUE TITLE
Epic: accessibility for exhibitions content

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#337]
- [x] empty heading (```<h2>``` contains no content)
   - #333 (Eliminate page-title/section-title markup at end of header)
 - [x] skipped heading level
   - #326 (improve hierarchy and and link structure in header on pages other than home)
- [x] redundant link at search affordance
   - #250 (hide advanced search from screen readers)
- [x] redundant title text in header links
   - #331 (eliminate all title attributes on links in header navigation)
- [x] redundant image and text links in "Mosaic Listing"
   - #338 (fix link and image markup in "Mosaic Listing")
- [x] unwanted title attributes on links in "Mosaic Listing"
   - #338 (fix link and image markup in "Mosaic Listing")
- [x] unwanted title attributes on images in "Mosaic Listing"
   - #338 (fix link and image markup in "Mosaic Listing")
- [x] unwanted title attribute on image in "Exhibition Object"
   - #329 (support alt text on exhibition objects images)
- [x] no way to create/edit "alt" text on "Exhibition Object" lead images
  - #329 (support alt text on exhibition objects images)
- [x] missing "alt" text on "Publication Object" thumbnail images
   - #340 (provide "alt" text for "Publication Object" thumbnail images)
- [x] no way to create/edit "alt" text on "Publication Object" lead images
   - #339 (support alt text on publication objects lead images)
 - [x] iterate support for "Exhibition Objects"
   - #274 (exhibition objects need iterate support)

**Comment by paregorios** [comment]
this epic is complete
