### ISSUE TITLE
migrate kinik content from standalone website to the research section of isaw web

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#411]
Steps:

 - [x] content migration: Move kinikhoyuk.org content to Plone site
 - [ ] Kinik team to verify completeness of migrated content
 - [ ] isaw it team to verify accessibility of migrated content and develop mitigation plan
 - [ ] "go live"

**Comment by paregorios** [comment]
Assigned to @k2soule to reflect the fact that she is liaising with the responsible faculty member regarding completeness (do we need a separate, subordinate ticket for that step?).
